## Упражнения по библиотеке Numpy

In [1]:
import numpy as np
import random
from math import prod
from collections import Counter
import math
from scipy.spatial.distance import cdist
import time

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(low=0, high=20, size=(10))
print("Original array:\n", arr)

arr = np.where((arr > 3) & (arr < 8), -arr, arr)
print("\nResult array:\n", arr)

Original array:
 [ 4  5 15  1 17 13 15 16 15 12]

Result array:
 [-4 -5 15  1 17 13 15 16 15 12]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(low=0, high=20, size=(10))
print("Original array:\n", arr)
arr[np.where(arr == np.max(arr))[0]] = 0
print("\nResult array:\n", arr)

Original array:
 [14 10  7  4 15  7  1 19  6 18]

Result array:
 [14 10  7  4 15  7  1  0  6 18]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr = np.array([[1, 2], [3, 4]])
flat_arr = arr.flatten()
result = np.array(np.meshgrid(flat_arr, flat_arr)).T.reshape(-1, 2)
print(result)

[[1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(low=0, high=5, size=(8, 3))
B = np.random.randint(low=0, high=5, size=(2, 2))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

res = np.full(shape=(8), fill_value=True)

for i in range(B.ndim):
    is_in_B = np.isin(A, B[i])
    is_in_B = np.any(is_in_B, axis=1)
    res = res & is_in_B

C = A[res, :]
print("\nResult:\n", C)

Matrix A:
 [[2 3 3]
 [2 1 1]
 [0 0 4]
 [2 1 2]
 [3 1 2]
 [2 2 1]
 [4 2 0]
 [0 0 2]]

Matrix B:
 [[2 3]
 [0 3]]

Result:
 [[2 3 3]
 [3 1 2]
 [4 2 0]
 [0 0 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
m = np.random.randint(low=0, high=2, size=(10, 3))
print("Original matrix: \n", m)

idx = np.apply_along_axis(lambda x: len(np.unique(x)) > 1, axis=1, arr=m)
print("\nResult matrix:\n", m[idx])

Original matrix: 
 [[0 1 1]
 [1 1 0]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 0 0]
 [1 0 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]]

Result matrix:
 [[0 1 1]
 [1 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 1]
 [1 0 1]
 [1 0 0]
 [0 1 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
arr = np.random.randint(low=0, high=2, size=(10, 3))
print("Original matrix:\n", arr)

arr = np.unique(arr, axis=0)
print("\nResult matrix:\n", arr)

Original matrix:
 [[1 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 1 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 1 0]
 [0 1 0]]

Result matrix:
 [[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
# Clear python

matrix = [[random.randint(0, 5) for _ in range(4)] for _ in range(4)]
print("Oroginal matrix:\n", matrix)

non_zero_diag = [matrix[i][i] for i in range(len(matrix)) if matrix[i][i] != 0]
product = prod(non_zero_diag)

print("\nResult:", product)

Oroginal matrix:
 [[1, 4, 1, 0], [2, 4, 4, 5], [5, 5, 1, 1], [2, 4, 5, 0]]

Result: 4


In [10]:
# Numpy

arr = np.random.randint(low=0, high=5, size=(4, 4))
print("Original matrix:\n", arr)

product = np.prod(arr.diagonal(), axis=0, where=(arr.diagonal() != 0))
print("\nResult:", product)

Original matrix:
 [[0 3 0 2]
 [2 3 4 1]
 [2 1 2 1]
 [2 2 3 4]]

Result: 24


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
# Clear python

A = [random.randint(1, 3) for _ in range(4)]
B = [random.randint(1, 3) for _ in range(4)]

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

A.sort()
B.sort()

are_multisets_equal = A == B
print("\nEqual multisets: ", are_multisets_equal)

Matrix A:
 [1, 3, 1, 2]

Matrix B:
 [1, 1, 2, 1]

Equal multisets:  False


In [12]:
# Numpy

A = np.random.randint(low=1, high=4, size=(4))
B = np.random.randint(low=1, high=4, size=(4))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

print("\nEqual multisets: ", np.all(np.sort(A) == np.sort(B)))

Matrix A:
 [3 3 3 1]

Matrix B:
 [3 1 3 1]

Equal multisets:  False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [13]:
# Clear python

arr = random.choices(range(10), weights=[0.5] + [0.05] * 9, k=10)
print("Original array:\n", arr)

max_val = None
for i in range(1, len(arr)):
    if arr[i - 1] == 0:
        if max_val is None or arr[i] > max_val:
            max_val = arr[i]
print("\nMax elem:", max_val)

Original array:
 [3, 7, 0, 0, 0, 9, 3, 0, 0, 0]

Max elem: 9


In [14]:
# Numpy

arr = np.random.choice(
    range(10), size=10, p=[0.55, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
)
print("Original array:\n", arr)

next_values = np.where(arr == 0)[0] + 1
max_val = np.max(arr[next_values[next_values < len(arr)]])
print("\nMax elem:", max_val)

Original array:
 [0 0 0 0 0 0 1 0 3 0]

Max elem: 3


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [15]:
# Clear python

arr = [random.randint(0, 6) for _ in range(7)]
print("Original array:\n", arr)

counter = Counter(arr)
counter_keys = list(counter.keys())
counter_values = list(counter.values())

print("\nResult:")
print(counter_keys)
print(counter_values)

Original array:
 [2, 4, 6, 4, 1, 2, 1]

Result:
[2, 4, 6, 1]
[2, 2, 1, 2]


In [16]:
# Numpy

arr = np.random.randint(low=0, high=5, size=(7))
print("Original array:\n", arr)

changes = np.concatenate(([1], np.diff(arr) != 0))
indices = np.nonzero(changes)[0]
values = arr[indices]
counts = np.diff(np.concatenate((indices, [len(arr)])))

print("\nResult:\n", (values, counts))

Original array:
 [3 3 0 3 1 0 0]

Result:
 (array([3, 0, 3, 1, 0]), array([2, 1, 1, 1, 2], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [21]:
# Only python
X = np.random.randint(0, 100, (100, 2))
Y = np.random.randint(0, 100, (100, 2))
distance_matrix = []

start_time = time.time()
for x in X:
    row = []
    for y in Y:
        distance = math.sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))
        row.append(distance)
    distance_matrix.append(row)
end_time = time.time()

print(distance_matrix)
print("\nTime taken (without numpy):", end_time - start_time)



# With Numpy
start_time = time.time()
distances = np.sqrt(((X[:, np.newaxis] - Y) ** 2).sum(axis=2))
end_time = time.time()

print("\nTime taken (Numpy):", end_time - start_time)



# With scipy.spatial.distance.cdist
start_time = time.time()
distances_cdist = cdist(X, Y)
end_time = time.time()

print("\nTime taken (scipy cdist):", end_time - start_time)

[[25.0, 37.12142238654117, 19.4164878389476, 56.79788728465171, 32.31098884280702, 54.12947441089743, 35.35533905932738, 38.05259518088089, 29.832867780352597, 29.966648127543394, 50.44799302251776, 10.770329614269007, 41.7612260356422, 31.953090617340916, 59.841457201508724, 81.39410298049853, 51.07837115648854, 24.041630560342615, 27.16615541441225, 26.92582403567252, 50.15974481593781, 61.09828148156051, 29.068883707497267, 36.0, 46.22769732530488, 78.64477096412705, 37.48332962798263, 24.698178070456937, 31.575306807693888, 29.410882339705484, 34.132096331752024, 26.68332812825267, 17.0, 26.076809620810597, 65.29931086925804, 50.48762224545735, 42.20189569201838, 74.2024258363566, 45.45327270945405, 59.665735560705194, 28.442925306655784, 45.967379738244816, 15.297058540778355, 28.0178514522438, 35.35533905932738, 33.83784863137726, 43.104524124504614, 59.665735560705194, 27.65863337187866, 48.38388161361178, 47.07440918375928, 84.17244204607586, 38.8329756778952, 51.07837115648854

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [22]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [23]:
file_path = './data/cereal.csv'

calorie_stats = np.loadtxt(file_path, delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [25]:
average_calories = np.average(calorie_stats)
print(f"Average calories: {average_calories:.2f}")
print(f"The average number of calories is {average_calories - 60:.2f} higher.\n")

Average calories: 106.88
The average number of calories is 46.88 higher.



3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [26]:
calorie_stats_sorted = np.sort(calorie_stats)
print("Sorted statistics: \n", calorie_stats_sorted, "\n")

Sorted statistics: 
 [ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.] 



4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [27]:
median_calories = np.median(calorie_stats_sorted)
print("Median:", median_calories, "\n")

Median: 110.0 



5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [28]:
percentiles_to_check = np.arange(0, 101, 1)
nth_percentile = None
for p in percentiles_to_check:
    percentile_value = np.percentile(calorie_stats, p)
    if percentile_value > 60:
        nth_percentile = p
        break
print("The smallest percentile exceeding 60 calories is:", nth_percentile, "\n")

The smallest percentile exceeding 60 calories is: 4 



6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [29]:
more_calories = round((np.sum(calorie_stats > 60) / len(calorie_stats)) * 100, 2)
print(f"Percentage of cereals with more than 60 calories: {more_calories:.2f}%\n")

Percentage of cereals with more than 60 calories: 96.10%



7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [30]:
calorie_std = np.std(calorie_stats)
print(f"Standard deviation of calories: {calorie_std:.2f}")

Standard deviation of calories: 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Анализ показал, что CrunchieMunchies выделяется на фоне конкурентов благодаря своему низкому содержанию калорий — всего 60 калорий на порцию. Среднее значение калорий у конкурентов значительно выше, а медиана показывает, что половина из них содержит более 100 калорий. Значительное стандартное отклонение подтверждает широкий разброс в калорийности, что подчеркивает уникальность CrunchieMunchies как низкокалорийного выбора, и эти данные можно эффективно использовать в маркетинге.